apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-server
spec:
    replicas: 5
    selector:
        matchLabels:
              app: app-server
    template:
        metadata:
            labels:
                app: app-server
        spec:
            containers:
                - name: spring-server
                  image: moisesvidal09/mongo:latest
                  ports:
                    - containerPort: 8080

