apiVersion: v1
kind: Service
metadata:
    name: spring-server-service
spec:
    type: ClusterIP
    ports:
        - protocol: TCP
          name: http-svc
          port: 8080
    selector:
        app: app-server
